# Generated by Django 5.1.4 on 2026-06-22 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(default='Gobierno Autónomo Descentralizado Provincial de Cotopaxi', max_length=200)),
                ('siglas_institucion', models.CharField(default='GAD COTOPAXI', max_length=20)),
                ('ruc_institucion', models.CharField(blank=True, max_length=13)),
                ('direccion', models.CharField(blank=True, default='Latacunga, Ecuador', max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('sitio_web', models.URLField(blank=True, default='https://cotopaxi.gob.ec')),
                ('email_institucional', models.EmailField(blank=True, default='sgd@cotopaxi.gob.ec', max_length=254)),
                ('logo_url', models.URLField(blank=True, default='https://cotopaxi.gob.ec/wp-content/uploads/2026/02/Prefectura-de-Cotopaxi-0062d2.svg')),
                ('numeracion_por_anio', models.BooleanField(default=True, help_text='Reinicia numeración cada año')),
                ('formato_numero', models.CharField(default='{PREFIJO}-{NUM}-{SIGLAS}-{ANIO}', help_text='Formato del número de documento', max_length=50)),
                ('dias_alerta_vencimiento', models.SmallIntegerField(default=3, help_text='Días antes del vencimiento para alertar')),
                ('smtp_host', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.SmallIntegerField(blank=True, null=True)),
                ('smtp_usuario', models.EmailField(blank=True, max_length=254)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_remitente', models.CharField(blank=True, max_length=200)),
                ('pie_pagina_pdf', models.TextField(blank=True, default='Gobierno Autónomo Descentralizado Provincial de Cotopaxi · Latacunga, Ecuador')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cfg_configuracion',
            },
        ),
    ]
