# Generated by Django 5.1.4 on 2026-09-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='abreviatura_institucion',
            field=models.CharField(default='GADPC', help_text='Código corto de la institución para la numeración documental (token "institucion", p. ej. GADPC-DA-2026-0455-C)', max_length=12),
        ),
    ]
