# Generated by Django 5.1.4 on 2026-06-10 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('tramites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recibido', 'Recibido'), ('enviado', 'Enviado'), ('interno', 'Interno')], default='recibido', max_length=20)),
                ('asunto', models.CharField(max_length=500)),
                ('cuerpo', models.TextField(blank=True)),
                ('remitente_email', models.EmailField(blank=True, max_length=200)),
                ('remitente_nombre', models.CharField(blank=True, max_length=200)),
                ('remitente_entidad', models.CharField(blank=True, max_length=200)),
                ('destinatarios_json', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('leido', 'Leído'), ('en_proceso', 'En proceso'), ('atendido', 'Atendido'), ('archivado', 'Archivado')], default='nuevo', max_length=20)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('muy_urgente', 'Muy urgente')], default='normal', max_length=20)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite_resp', models.DateField(blank=True, null=True)),
                ('respondido', models.BooleanField(default=False)),
                ('num_adjuntos', models.SmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('correo_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='correos.correo')),
                ('doc_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.documento')),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tramites.tramite')),
                ('unidad_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_recibidos', to='organizacion.unidad')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cor_correo',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(max_length=100)),
                ('tamano_bytes', models.BigIntegerField()),
                ('archivo_lo', models.IntegerField()),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='correos.correo')),
            ],
            options={
                'db_table': 'cor_adjunto',
            },
        ),
        migrations.AddIndex(
            model_name='correo',
            index=models.Index(fields=['estado'], name='cor_correo_estado_6ff1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='correo',
            index=models.Index(fields=['unidad_destino'], name='cor_correo_unidad__2cc6c1_idx'),
        ),
        migrations.AddIndex(
            model_name='correo',
            index=models.Index(fields=['fecha_recepcion'], name='cor_correo_fecha_r_9ec2ed_idx'),
        ),
    ]
