# Generated by Django 5.1.4 on 2026-06-10 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0001_initial'),
        ('documentos', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('tramites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('recibido', 'Recibido'), ('registrado', 'Registrado'), ('asignado', 'Asignado'), ('respuesta', 'Respuesta enviada'), ('archivado', 'Archivado')], max_length=20)),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cor_seguimiento',
                'ordering': ['creado_en'],
            },
        ),
        migrations.RemoveField(
            model_name='correo',
            name='tramite',
        ),
        migrations.AddField(
            model_name='correo',
            name='etiquetas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='correo',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='correo',
            name='leido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='numero_registro',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='correo',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correo',
            name='tramite_generado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_origen', to='tramites.tramite'),
        ),
        migrations.AlterField(
            model_name='adjuntocorreo',
            name='archivo_lo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='correo',
            name='doc_generado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_origen', to='documentos.documento'),
        ),
        migrations.AlterField(
            model_name='correo',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('registrado', 'Registrado'), ('asignado', 'Asignado'), ('en_proceso', 'En proceso'), ('respondido', 'Respondido'), ('archivado', 'Archivado')], default='nuevo', max_length=20),
        ),
        migrations.AddIndex(
            model_name='correo',
            index=models.Index(fields=['numero_registro'], name='cor_correo_numero__197dff_idx'),
        ),
        migrations.AddField(
            model_name='seguimientocorreo',
            name='correo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='correos.correo'),
        ),
        migrations.AddField(
            model_name='seguimientocorreo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_correo', to=settings.AUTH_USER_MODEL),
        ),
    ]
