# Generated by Django 5.1.4 on 2026-06-09 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.SmallIntegerField(default=99)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usr_rol',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('funcionario', 'Funcionario'), ('ciudadano', 'Ciudadano'), ('sistema', 'Sistema')], default='funcionario', max_length=20)),
                ('cedula', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('email_institucional', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=20)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=200)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('firma_electronica', models.BooleanField(default=False)),
                ('cert_bce_serial', models.CharField(blank=True, max_length=100)),
                ('cert_bce_expira', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('bloqueado', models.BooleanField(default=False)),
                ('motivo_bloqueo', models.TextField(blank=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('intentos_fallidos', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('unidad', models.ForeignKey(blank=True, db_column='unidad_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='organizacion.unidad')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usr_usuario',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jti', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('dispositivo', models.CharField(blank=True, max_length=50)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_seg', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('expirada', 'Expirada'), ('revocada', 'Revocada')], default='activa', max_length=20)),
                ('motivo_cierre', models.CharField(blank=True, max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usr_sesion',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField(auto_now_add=True)),
                ('hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_asignados', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.unidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usr_usuario_rol',
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['cedula'], name='usr_usuario_cedula_5404a9_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='usr_usuario_email_de46dd_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['tipo'], name='usr_usuario_tipo_579386_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['activo'], name='usr_usuario_activo_b68e4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together={('usuario', 'rol', 'unidad')},
        ),
    ]
