# Generated by Django 5.1.4 on 2026-06-18 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariorol',
            name='asignado_por',
            field=models.ForeignKey(blank=True, db_column='asignado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
