# Generated by Django 5.1.4 on 2026-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuariorol_asignado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo_tipo',
            field=models.SmallIntegerField(default=0, help_text='0=normal, 1=jefe, 2=asistente'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='titulo',
            field=models.CharField(blank=True, help_text='Abreviatura del titulo: Sr. Ing., Sra. Mgs., etc.', max_length=50),
        ),
    ]
