# Generated by Django 5.1.4 on 2026-06-10 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('icono', models.CharField(blank=True, max_length=60)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.SmallIntegerField(default=99)),
            ],
            options={
                'db_table': 'tra_categoria',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='natural', max_length=20)),
                ('tipo_identificacion', models.CharField(choices=[('cedula', 'Cédula'), ('ruc', 'RUC'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], default='cedula', max_length=20)),
                ('numero_identificacion', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(blank=True, max_length=150)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('representante_legal', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('email_alternativo', models.EmailField(blank=True, max_length=200)),
                ('telefono_movil', models.CharField(blank=True, max_length=20)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20)),
                ('provincia', models.CharField(blank=True, max_length=80)),
                ('canton', models.CharField(blank=True, max_length=80)),
                ('parroquia', models.CharField(blank=True, max_length=80)),
                ('direccion', models.TextField(blank=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('nacionalidad', models.CharField(default='Ecuatoriana', max_length=60)),
                ('notificacion_email', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ciu_persona',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='TipoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('base_legal', models.TextField(blank=True)),
                ('dias_plazo', models.SmallIntegerField(default=15)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requiere_inspeccion', models.BooleanField(default=False)),
                ('en_linea', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos', to='tramites.categoria')),
                ('unidad_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.unidad')),
            ],
            options={
                'db_table': 'tra_tipo_tramite',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('obligatorio', models.BooleanField(default=True)),
                ('formato_aceptado', models.CharField(default='pdf', max_length=100)),
                ('orden', models.SmallIntegerField(default=99)),
                ('tipo_tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='tramites.tipotramite')),
            ],
            options={
                'db_table': 'tra_requisito',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('numero_tramite', models.CharField(max_length=30, unique=True)),
                ('canal_ingreso', models.CharField(choices=[('ventanilla', 'Ventanilla'), ('web', 'Portal web'), ('email', 'Correo electrónico'), ('oficio', 'Oficio'), ('telefono', 'Teléfono')], default='ventanilla', max_length=30)),
                ('asunto', models.CharField(max_length=500)),
                ('detalle', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('asignado', 'Asignado'), ('en_proceso', 'En proceso'), ('en_inspeccion', 'En inspección'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado'), ('desistido', 'Desistido'), ('archivado', 'Archivado')], default='ingresado', max_length=30)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('muy_urgente', 'Muy urgente')], default='normal', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('dias_resolucion', models.SmallIntegerField(blank=True, null=True)),
                ('dentro_plazo', models.BooleanField(blank=True, null=True)),
                ('tipo_resolucion', models.CharField(blank=True, choices=[('favorable', 'Favorable'), ('desfavorable', 'Desfavorable'), ('derivado', 'Derivado'), ('desistido', 'Desistido'), ('improcedente', 'Improcedente')], max_length=30)),
                ('resolucion_texto', models.TextField(blank=True)),
                ('calificacion', models.SmallIntegerField(blank=True, null=True)),
                ('comentario_ciudadano', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramites', to='tramites.persona')),
                ('tipo_tramite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tramites.tipotramite')),
                ('unidad_receptora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramites_recibidos', to='organizacion.unidad')),
                ('unidad_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramites_responsables', to='organizacion.unidad')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites_asignados', to=settings.AUTH_USER_MODEL)),
                ('usuario_receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tra_tramite',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('observacion', models.TextField(blank=True)),
                ('visible_ciudadano', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.unidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='tramites.tramite')),
            ],
            options={
                'db_table': 'tra_seguimiento',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(max_length=100)),
                ('tamano_bytes', models.BigIntegerField()),
                ('archivo_lo', models.IntegerField()),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('tipo_adjunto', models.CharField(choices=[('ciudadano', 'Del ciudadano'), ('sistema', 'Del sistema'), ('resolucion', 'Resolución'), ('notificacion', 'Notificación'), ('inspeccion', 'Inspección')], default='ciudadano', max_length=30)),
                ('verificado', models.BooleanField(default=False)),
                ('verificado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_verificados', to=settings.AUTH_USER_MODEL)),
                ('requisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tramites.requisito')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tramites.tramite')),
            ],
            options={
                'db_table': 'tra_documento_adjunto',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['numero_identificacion'], name='ciu_persona_numero__3b30e2_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['email'], name='ciu_persona_email_183607_idx'),
        ),
        migrations.AddIndex(
            model_name='tramite',
            index=models.Index(fields=['numero_tramite'], name='tra_tramite_numero__5e069a_idx'),
        ),
        migrations.AddIndex(
            model_name='tramite',
            index=models.Index(fields=['estado'], name='tra_tramite_estado_94146a_idx'),
        ),
        migrations.AddIndex(
            model_name='tramite',
            index=models.Index(fields=['fecha_limite'], name='tra_tramite_fecha_l_d2a3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='tramite',
            index=models.Index(fields=['persona'], name='tra_tramite_persona_12e81b_idx'),
        ),
    ]
