# Generated by Django 5.1.4 on 2026-08-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='canal_ingreso',
            field=models.CharField(choices=[('ventanilla', 'Ventanilla'), ('email', 'Correo electrónico'), ('web', 'Digital / Web')], default='ventanilla', max_length=30),
        ),
    ]
