# Generated by Django 5.1.4 on 2026-08-20 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0002_alter_tramite_canal_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='fecha_documento',
            field=models.DateField(blank=True, help_text='Fecha que consta en el oficio recibido (distinta de fecha_ingreso)', null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='firmante_oficio',
            field=models.CharField(blank=True, help_text='Quien firma el oficio, en texto libre — no depende de persona', max_length=200),
        ),
        migrations.AddField(
            model_name='tramite',
            name='numero_oficio',
            field=models.CharField(blank=True, help_text='Numeración institucional del oficio; puede ser "S/N"', max_length=50),
        ),
        migrations.AddField(
            model_name='tramite',
            name='procedencia',
            field=models.CharField(blank=True, help_text='Institución/organización/persona de la que proviene el oficio', max_length=200),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites', to='tramites.persona'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='tipo_tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tramites.tipotramite'),
        ),
    ]
