# Generated by Django 5.1.4 on 2026-08-21 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
        ('tramites', '0003_tramite_fecha_documento_tramite_firmante_oficio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='unidad_receptora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites_recibidos', to='organizacion.unidad'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='unidad_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites_responsables', to='organizacion.unidad'),
        ),
    ]
