# Generated by Django 5.1.4 on 2026-08-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0004_alter_tramite_unidad_receptora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='cargo_firmante',
            field=models.CharField(blank=True, help_text='Cargo de quien firma el oficio', max_length=150),
        ),
        migrations.AddField(
            model_name='tramite',
            name='correo_contacto',
            field=models.EmailField(blank=True, help_text='Correo de contacto vigente para este trámite (no depende de Persona)', max_length=200),
        ),
        migrations.AddField(
            model_name='tramite',
            name='telefono_contacto',
            field=models.CharField(blank=True, help_text='Teléfono de contacto vigente para este trámite (no depende de Persona)', max_length=20),
        ),
    ]
