# Generated by Django 5.1.4 on 2026-08-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0005_tramite_cargo_firmante_tramite_correo_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
