# Generated by Django 5.1.4 on 2026-08-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0006_alter_persona_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='cedula_firmante',
            field=models.CharField(blank=True, help_text='Identificación (cédula/RUC) del firmante registrada para este trámite — snapshot histórico, no depende de Persona', max_length=20, null=True),
        ),
    ]
