# Generated by Django 5.1.4 on 2026-06-09 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'org_funcion',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.SmallIntegerField(default=99)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'org_nivel',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_corto', models.CharField(blank=True, max_length=80)),
                ('siglas', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('prefectura', 'Prefectura'), ('viceprefectura', 'Viceprefectura'), ('consejo', 'Consejo Provincial'), ('direccion', 'Dirección'), ('unidad', 'Unidad'), ('coordinacion', 'Coordinación'), ('secretaria', 'Secretaría'), ('asesoria', 'Asesoría'), ('procuraduria', 'Procuraduría'), ('zona', 'Zona/Sistema')], max_length=30)),
                ('mision', models.TextField(blank=True)),
                ('responsable_id', models.IntegerField(blank=True, null=True)),
                ('email_oficial', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('piso_ubicacion', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('orden_display', models.SmallIntegerField(default=99)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('funcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.funcion')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.nivel')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='organizacion.unidad')),
            ],
            options={
                'db_table': 'org_unidad',
                'ordering': ['orden_display', 'nombre'],
                'indexes': [models.Index(fields=['padre'], name='org_unidad_padre_i_6aa189_idx'), models.Index(fields=['activo'], name='org_unidad_activo_7ccee1_idx'), models.Index(fields=['tipo'], name='org_unidad_tipo_a6c8a7_idx')],
            },
        ),
    ]
