# Generated by Django 5.1.4 on 2026-06-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=60)),
                ('registro_id', models.BigIntegerField(blank=True, null=True)),
                ('accion', models.CharField(choices=[('INSERT', 'Creación'), ('UPDATE', 'Modificación'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('FIRMA', 'Firma electrónica'), ('DESCARGA', 'Descarga'), ('VISTA', 'Vista'), ('ANULACION', 'Anulación')], max_length=20)),
                ('datos_antes', models.JSONField(blank=True, null=True)),
                ('datos_despues', models.JSONField(blank=True, null=True)),
                ('campos_cambiados', models.TextField(blank=True, null=True)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('usuario_email', models.CharField(blank=True, max_length=200)),
                ('unidad_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('modulo', models.CharField(blank=True, max_length=40)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aud_log',
                'ordering': ['-creado_en'],
                'managed': False,
            },
        ),
    ]
