# Generated by Django 5.1.4 on 2026-06-10 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('prefijo_numeracion', models.CharField(max_length=20)),
                ('requiere_firma', models.BooleanField(default=False)),
                ('requiere_aprobacion', models.BooleanField(default=False)),
                ('dias_plazo_default', models.SmallIntegerField(default=15)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.SmallIntegerField(default=99)),
            ],
            options={
                'db_table': 'doc_tipo_documento',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_documento', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('anio', models.SmallIntegerField()),
                ('numero_secuencial', models.IntegerField(blank=True, null=True)),
                ('asunto', models.CharField(max_length=500)),
                ('cuerpo', models.TextField(blank=True)),
                ('resumen', models.TextField(blank=True)),
                ('palabras_clave', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('enviado', 'Enviado'), ('recibido', 'Recibido'), ('archivado', 'Archivado'), ('anulado', 'Anulado')], default='borrador', max_length=30)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('muy_urgente', 'Muy urgente')], default='normal', max_length=20)),
                ('confidencial', models.BooleanField(default=False)),
                ('requiere_respuesta', models.BooleanField(default=False)),
                ('fecha_limite_resp', models.DateField(blank=True, null=True)),
                ('fecha_elaboracion', models.DateField(auto_now_add=True)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_archivo', models.DateTimeField(blank=True, null=True)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('firma_bce_info', models.JSONField(blank=True, null=True)),
                ('num_paginas', models.SmallIntegerField(blank=True, null=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('vistas', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_anulados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_creados', to=settings.AUTH_USER_MODEL)),
                ('firmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_firmados', to=settings.AUTH_USER_MODEL)),
                ('relacionado_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relacionados', to='documentos.documento')),
                ('responde_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='documentos.documento')),
                ('unidad_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_recibidos', to='organizacion.unidad')),
                ('unidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_emitidos', to='organizacion.unidad')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.tipodocumento')),
            ],
            options={
                'db_table': 'doc_documento',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('copia', 'Copia'), ('conocimiento', 'Conocimiento')], default='principal', max_length=20)),
                ('leido', models.BooleanField(default=False)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('accion_tomada', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('atendido', 'Atendido'), ('archivado', 'Archivado'), ('derivado', 'Derivado')], default='pendiente', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizacion.unidad')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='documentos.documento')),
            ],
            options={
                'db_table': 'doc_destinatario',
            },
        ),
        migrations.CreateModel(
            name='FlujoAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso_numero', models.SmallIntegerField()),
                ('tipo_accion', models.CharField(choices=[('elaboracion', 'Elaboración'), ('revision', 'Revisión'), ('aprobacion', 'Aprobación'), ('firma', 'Firma'), ('envio', 'Envío')], max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('omitido', 'Omitido'), ('en_proceso', 'En proceso')], default='pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujo', to='documentos.documento')),
            ],
            options={
                'db_table': 'doc_flujo_aprobacion',
                'ordering': ['paso_numero'],
            },
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.SmallIntegerField()),
                ('cuerpo', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='documentos.documento')),
            ],
            options={
                'db_table': 'doc_version',
                'ordering': ['-numero_version'],
            },
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tipo_documento'], name='doc_documen_tipo_do_9382df_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['estado'], name='doc_documen_estado_d370e9_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['unidad_origen'], name='doc_documen_unidad__ad383c_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['anio'], name='doc_documen_anio_488cab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='versiondocumento',
            unique_together={('documento', 'numero_version')},
        ),
    ]
