# Generated by Django 5.1.4 on 2026-06-12 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinatarioExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('institucion', 'Institución externa'), ('ciudadano', 'Ciudadano')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('institucion', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('cedula_ruc', models.CharField(blank=True, max_length=20)),
                ('enviado', models.BooleanField(default=False)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('notificado_email', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios_externos', to='documentos.documento')),
            ],
            options={
                'db_table': 'doc_destinatario_externo',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('elaborado', 'Elaborado'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('recibido', 'Recibido'), ('reasignado', 'Reasignado'), ('informado', 'Informado'), ('comentado', 'Comentado'), ('archivado', 'Archivado'), ('respondido', 'Respondido')], max_length=20)),
                ('destinatario_externo', models.CharField(blank=True, max_length=200)),
                ('institucion_externa', models.CharField(blank=True, max_length=200)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_quipux', to='documentos.documento')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.unidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc_seguimiento',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('muy_urgente', 'Muy urgente')], default='normal', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignada_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('asignada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='documentos.documento')),
                ('unidad_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.unidad')),
            ],
            options={
                'db_table': 'doc_tarea',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='BandejaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeja', models.CharField(choices=[('recibidos', 'Recibidos'), ('en_elaboracion', 'En elaboración'), ('enviados', 'Enviados'), ('no_enviados', 'No enviados'), ('tareas_recibidas', 'Tareas recibidas'), ('tareas_enviadas', 'Tareas enviadas'), ('archivados', 'Archivados'), ('por_imprimir', 'Por imprimir')], max_length=30)),
                ('accion_tomada', models.CharField(choices=[('pendiente', 'Pendiente'), ('leido', 'Leído'), ('reasignado', 'Reasignado'), ('informado', 'Informado'), ('archivado', 'Archivado'), ('comentado', 'Comentado'), ('respondido', 'Respondido')], default='pendiente', max_length=20)),
                ('leido', models.BooleanField(default=False)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('es_urgente', models.BooleanField(default=False)),
                ('numero_referencia', models.CharField(blank=True, max_length=60)),
                ('instrucciones', models.TextField(blank=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandejas', to='documentos.documento')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizacion.unidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandeja_documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc_bandeja',
                'indexes': [models.Index(fields=['usuario', 'bandeja'], name='doc_bandeja_usuario_8ac11b_idx'), models.Index(fields=['leido'], name='doc_bandeja_leido_56521f_idx')],
                'unique_together': {('documento', 'usuario', 'bandeja')},
            },
        ),
    ]
