# Generated by Django 5.1.4 on 2026-06-12 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_destinatarioexterno_seguimientodocumento_tarea_and_more'),
        ('tramites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='adjuntos/%Y/%m/')),
                ('tipo', models.CharField(choices=[('documento', 'Documento principal'), ('anexo', 'Anexo'), ('respaldo', 'Respaldo'), ('otro', 'Otro')], default='anexo', max_length=20)),
                ('tamanio', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='documentos.documento')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='tramites.tramite')),
            ],
            options={
                'db_table': 'doc_adjunto',
                'ordering': ['-creado_en'],
            },
        ),
    ]