# Generated by Django 5.1.4 on 2026-06-17 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_adjuntodocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntodocumento',
            name='calidad_control',
            field=models.CharField(choices=[('pendiente', 'Pendiente de control de calidad'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado — requiere nueva digitalización')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='calidad_observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='calidad_revisado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='calidad_revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_calidad_revisada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='digitalizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_digitalizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='fecha_digitalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='formato_archivo',
            field=models.CharField(blank=True, help_text='PDF/A, TIFF, JPEG, etc.', max_length=10),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='hash_integridad',
            field=models.CharField(blank=True, help_text='SHA-256 del archivo para verificación de integridad', max_length=64),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='hoja_testigo',
            field=models.BooleanField(default=False, help_text='Indica si el original físico permanece en archivo con hoja testigo'),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='numero_folios',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='origen_digitalizacion',
            field=models.CharField(blank=True, choices=[('institucional', 'Digitalización institucional (300 ppp)'), ('quipux', 'Recibido vía Quipux (90 ppp)'), ('nativo_digital', 'Nativo digital (no requiere digitalización)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='resolucion_ppp',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Puntos por pulgada de la digitalización (300 institucional, 90 Quipux)', null=True),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, help_text='Caja/estante donde reposa el original físico, si aplica', max_length=200),
        ),
    ]
