# Generated by Django 5.1.4 on 2026-06-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_adjuntodocumento_calidad_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='etiquetas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documento',
            name='remitente_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documento',
            name='remitente_entidad',
            field=models.CharField(blank=True, help_text='Institución externa remitente, ej: Contraloría General del Estado', max_length=200),
        ),
        migrations.AddField(
            model_name='documento',
            name='remitente_nombre',
            field=models.CharField(blank=True, help_text='Nombre de quien remite, si el documento proviene de fuera del GAD', max_length=200),
        ),
    ]
