# Generated by Django 5.1.4 on 2026-06-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_documento_etiquetas_documento_remitente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntodocumento',
            name='contenido_texto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='idioma_ocr',
            field=models.CharField(blank=True, default='spa', max_length=10),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='ocr_confianza',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='ocr_procesado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adjuntodocumento',
            name='paginas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adjuntodocumento',
            name='hash_integridad',
            field=models.CharField(blank=True, max_length=64),
        ),
        # Columna tsvector para búsqueda full-text
        migrations.RunSQL(
            sql="""
                ALTER TABLE doc_adjunto
                ADD COLUMN IF NOT EXISTS contenido_busqueda tsvector;

                UPDATE doc_adjunto
                SET contenido_busqueda = to_tsvector('spanish', COALESCE(contenido_texto, ''))
                WHERE contenido_texto != '';

                CREATE INDEX IF NOT EXISTS idx_doc_adjunto_busqueda
                ON doc_adjunto USING GIN(contenido_busqueda);

                CREATE OR REPLACE FUNCTION fn_actualizar_busqueda_adjunto()
                RETURNS TRIGGER AS $$
                BEGIN
                    NEW.contenido_busqueda :=
                        to_tsvector('spanish', COALESCE(NEW.contenido_texto, ''));
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                DROP TRIGGER IF EXISTS trg_busqueda_adjunto ON doc_adjunto;
                CREATE TRIGGER trg_busqueda_adjunto
                BEFORE INSERT OR UPDATE OF contenido_texto
                ON doc_adjunto
                FOR EACH ROW
                EXECUTE FUNCTION fn_actualizar_busqueda_adjunto();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS trg_busqueda_adjunto ON doc_adjunto;
                DROP FUNCTION IF EXISTS fn_actualizar_busqueda_adjunto();
                DROP INDEX IF EXISTS idx_doc_adjunto_busqueda;
                ALTER TABLE doc_adjunto DROP COLUMN IF EXISTS contenido_busqueda;
            """,
        ),
    ]