# Generated by Django 5.1.4 on 2026-06-24 18:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_adjunto_fulltext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='palabras_clave',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
