# Generated by Django 5.1.4 on 2026-06-24 18:00
#
# NOTA: el AlterField original generado por Django fallaba al recrear la
# base desde cero (p.ej. base de datos de pruebas) porque Postgres no
# puede convertir implícitamente jsonb -> varchar(100)[]. Ya está aplicada
# en la base real (no se re-ejecuta ahí); este RunSQL solo corrige el
# camino de instalación limpia, con el mismo resultado final de esquema.
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_adjunto_fulltext'),
    ]

    operations = [
        migrations.RunSQL(
            # Postgres no permite subconsultas dentro de ALTER ... TYPE ... USING,
            # así que se convierte con una columna temporal + UPDATE en su lugar.
            sql="""
                ALTER TABLE doc_documento ADD COLUMN palabras_clave_tmp varchar(100)[];
                UPDATE doc_documento SET palabras_clave_tmp =
                    ARRAY(SELECT jsonb_array_elements_text(COALESCE(palabras_clave, '[]'::jsonb)));
                ALTER TABLE doc_documento DROP COLUMN palabras_clave;
                ALTER TABLE doc_documento RENAME COLUMN palabras_clave_tmp TO palabras_clave;
                ALTER TABLE doc_documento ALTER COLUMN palabras_clave SET DEFAULT '{}';
                ALTER TABLE doc_documento ALTER COLUMN palabras_clave SET NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE doc_documento ADD COLUMN palabras_clave_tmp jsonb;
                UPDATE doc_documento SET palabras_clave_tmp = to_jsonb(palabras_clave);
                ALTER TABLE doc_documento DROP COLUMN palabras_clave;
                ALTER TABLE doc_documento RENAME COLUMN palabras_clave_tmp TO palabras_clave;
                ALTER TABLE doc_documento ALTER COLUMN palabras_clave SET DEFAULT '[]';
                ALTER TABLE doc_documento ALTER COLUMN palabras_clave SET NOT NULL;
            """,
            state_operations=[
                migrations.AlterField(
                    model_name='documento',
                    name='palabras_clave',
                    field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
                ),
            ],
        ),
    ]
