# Generated by Django 5.1.4 on 2026-06-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_alter_documento_palabras_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('firmado', 'Firmado'), ('aprobado', 'Aprobado'), ('enviado', 'Enviado'), ('recibido', 'Recibido'), ('archivado', 'Archivado'), ('anulado', 'Anulado')], default='borrador', max_length=30),
        ),
    ]
