# Generated by Django 5.1.4 on 2026-07-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_quipuxbandeja_sgd'),
    ]

    operations = [
        migrations.AddField(
            model_name='quipuxbandejasgd',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quipuxbandejasgd',
            name='leido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
