# Generated by Django 5.1.4 on 2026-07-03 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_quipuxbandeja_leido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuipuxContenidoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radi_nume_text', models.CharField(db_index=True, max_length=60, unique=True)),
                ('arch_codi', models.IntegerField()),
                ('contenido_texto', models.TextField(blank=True)),
                ('tiene_contenido', models.BooleanField(default=False)),
                ('es_escaneado', models.BooleanField(default=False)),
                ('procesado_en', models.DateTimeField(auto_now_add=True)),
                ('error_extraccion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'doc_quipux_contenido',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='quipux_origen',
            field=models.CharField(blank=True, help_text='radi_nume_text del documento Quipux al que este responde', max_length=60),
        ),
        migrations.CreateModel(
            name='QuipuxTareaAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea_codi', models.IntegerField(db_index=True)),
                ('avance', models.SmallIntegerField()),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quipux_avances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc_quipux_tarea_avance',
                'ordering': ['-creado_en'],
            },
        ),
    ]
