# Generated by Django 5.1.4 on 2026-07-08 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0012_tipodocumento_secuencial_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='remitente',
            field=models.ForeignKey(blank=True, help_text='Firmante previsto cuando es distinto al creador', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_como_remitente', to=settings.AUTH_USER_MODEL),
        ),
    ]
