# Generated by Django 5.1.4 on 2026-07-08 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0013_remitente_en_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('quipux_id', models.IntegerField(blank=True, help_text='lista_codi en Quipux (para deduplicar importaciones)', null=True, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_distribucion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc_lista_distribucion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ListaDistribucionMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.SmallIntegerField(default=0)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='documentos.listadistribucion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_como_miembro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc_lista_distribucion_miembro',
                'ordering': ['orden', 'usuario__apellidos'],
                'unique_together': {('lista', 'usuario')},
            },
        ),
    ]
