# Generated by Django 5.1.4 on 2026-08-13 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0014_lista_distribucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='motivo_eliminacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bandejadocumento',
            name='accion_tomada',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('leido', 'Leído'), ('reasignado', 'Reasignado'), ('informado', 'Informado'), ('archivado', 'Archivado'), ('comentado', 'Comentado'), ('respondido', 'Respondido'), ('eliminado', 'Eliminado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='bandejadocumento',
            name='bandeja',
            field=models.CharField(choices=[('recibidos', 'Recibidos'), ('en_elaboracion', 'En elaboración'), ('enviados', 'Enviados'), ('no_enviados', 'No enviados'), ('tareas_recibidas', 'Tareas recibidas'), ('tareas_enviadas', 'Tareas enviadas'), ('archivados', 'Archivados'), ('por_imprimir', 'Por imprimir'), ('eliminados', 'Eliminados')], max_length=30),
        ),
        migrations.AlterField(
            model_name='seguimientodocumento',
            name='etapa',
            field=models.CharField(choices=[('elaborado', 'Elaborado'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('recibido', 'Recibido'), ('reasignado', 'Reasignado'), ('informado', 'Informado'), ('comentado', 'Comentado'), ('archivado', 'Archivado'), ('respondido', 'Respondido'), ('recuperado', 'Recuperado'), ('eliminado', 'Eliminado'), ('restaurado', 'Restaurado')], max_length=20),
        ),
    ]
