# Generated by Django 5.1.4 on 2026-09-01 18:39

import apps.documentos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0015_documento_eliminado_en_documento_eliminado_por_and_more'),
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjuntodocumento',
            options={'ordering': ['creado_en']},
        ),
        migrations.CreateModel(
            name='ConfiguracionNumeracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviatura', models.CharField(blank=True, max_length=8)),
                ('separador', models.CharField(default='-', max_length=3)),
                ('digitos_anio', models.PositiveSmallIntegerField(default=4)),
                ('digitos_secuencia', models.PositiveSmallIntegerField(default=4)),
                ('estructura', models.JSONField(default=apps.documentos.models._estructura_numeracion_default)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_numeracion', to='documentos.tipodocumento')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_numeracion', to='organizacion.unidad')),
            ],
            options={
                'db_table': 'doc_config_numeracion',
                'constraints': [models.UniqueConstraint(fields=('unidad', 'tipo_documento'), name='uq_config_num_unidad_tipo')],
            },
        ),
        migrations.CreateModel(
            name='SecuenciaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('ultimo_provisional', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencias', to='documentos.tipodocumento')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencias', to='organizacion.unidad')),
            ],
            options={
                'db_table': 'doc_secuencia',
                'constraints': [models.UniqueConstraint(fields=('unidad', 'tipo_documento', 'anio'), name='uq_secuencia_unidad_tipo_anio')],
            },
        ),
        # Auditoría (§24) — SOLO sobre la config de formato (cambios de baja
        # frecuencia). `doc_secuencia` NO se audita por trigger: se
        # incrementaría en cada documento y saturaría aud_log; el ajuste
        # MANUAL de secuencia registra su propia entrada de auditoría.
        # `fn_auditoria` se aplica fuera de las migraciones (igual que el resto
        # de trg_auditoria_*). Solo se engancha el trigger si la función
        # existe — así una BD de test sin ella no falla.
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'fn_auditoria') THEN
                        DROP TRIGGER IF EXISTS trg_auditoria_doc_config_numeracion ON doc_config_numeracion;
                        CREATE TRIGGER trg_auditoria_doc_config_numeracion
                        AFTER INSERT OR UPDATE OR DELETE ON doc_config_numeracion
                        FOR EACH ROW EXECUTE FUNCTION fn_auditoria();
                    END IF;
                END $$;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS trg_auditoria_doc_config_numeracion ON doc_config_numeracion;",
        ),
    ]
