# Generated by Django 5.1.4 on 2026-09-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0016_numeracion_configurable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandejadocumento',
            name='bandeja',
            field=models.CharField(choices=[('recibidos', 'Recibidos'), ('en_elaboracion', 'En elaboración'), ('enviados', 'Enviados'), ('no_enviados', 'No enviados'), ('tareas_recibidas', 'Tareas recibidas'), ('tareas_enviadas', 'Tareas enviadas'), ('archivados', 'Archivados'), ('por_imprimir', 'Por imprimir'), ('eliminados', 'Eliminados'), ('informados', 'Informados')], max_length=30),
        ),
    ]
