# Generated by Django 5.1.4 on 2026-09-02 17:19
#
# MIGRACIÓN DE ESQUEMA únicamente. NO realiza conversión de datos: el backfill
# de `bandeja_origen` para documentos ya archivados corresponde al ETL de
# QUIPUX → SGDA (con acceso a radi_nume_radi / esta_codi / histórico), donde se
# aplican reglas verificadas. Ver `MIGRACION_QUIPUX_ARCHIVADOS.md`.
#
# Los ítems existentes con bandeja='archivados' quedan con bandeja_origen=NULL;
# "Restaurar" los rechaza con un mensaje explícito hasta que se pueble el
# origen — nunca se adivina.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0017_bandeja_informados'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandejadocumento',
            name='bandeja_origen',
            field=models.CharField(blank=True, choices=[('recibidos', 'Recibidos'), ('enviados', 'Enviados')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seguimientodocumento',
            name='etapa',
            field=models.CharField(choices=[('elaborado', 'Elaborado'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('recibido', 'Recibido'), ('reasignado', 'Reasignado'), ('informado', 'Informado'), ('comentado', 'Comentado'), ('archivado', 'Archivado'), ('desarchivado', 'Restaurado de archivados'), ('respondido', 'Respondido'), ('recuperado', 'Recuperado'), ('eliminado', 'Eliminado'), ('restaurado', 'Restaurado')], max_length=20),
        ),
    ]
