# Generated by Django 5.1.4 on 2026-09-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0018_bandeja_origen_archivados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientodocumento',
            name='etapa',
            field=models.CharField(choices=[('elaborado', 'Elaborado'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('recibido', 'Recibido'), ('reasignado', 'Reasignado'), ('informado', 'Informado'), ('comentado', 'Comentado'), ('archivado', 'Archivado'), ('desarchivado', 'Restaurado de archivados'), ('respondido', 'Respondido'), ('recuperado', 'Recuperado'), ('eliminado', 'Eliminado'), ('restaurado', 'Restaurado'), ('tarea_creada', 'Tarea creada'), ('tarea_iniciada', 'Tarea iniciada'), ('tarea_completada', 'Tarea completada'), ('tarea_cancelada', 'Tarea cancelada')], max_length=20),
        ),
    ]
