# Generated by Django 5.1.4 on 2026-09-02 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0019_tarea_etapas_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientodocumento',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to='documentos.tarea'),
        ),
    ]
