# Generated by Django 5.1.4 on 2026-09-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0020_seguimiento_tarea_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientodocumento',
            name='documento_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documentos.documento'),
        ),
        migrations.AlterField(
            model_name='seguimientodocumento',
            name='etapa',
            field=models.CharField(choices=[('elaborado', 'Elaborado'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('recibido', 'Recibido'), ('reasignado', 'Reasignado'), ('informado', 'Informado'), ('comentado', 'Comentado'), ('archivado', 'Archivado'), ('desarchivado', 'Restaurado de archivados'), ('respondido', 'Respondido'), ('recuperado', 'Recuperado'), ('eliminado', 'Eliminado'), ('restaurado', 'Restaurado'), ('tarea_creada', 'Tarea creada'), ('tarea_iniciada', 'Tarea iniciada'), ('tarea_completada', 'Tarea completada'), ('tarea_cancelada', 'Tarea cancelada'), ('asociado', 'Documento asociado'), ('desasociado', 'Documento desasociado')], max_length=20),
        ),
    ]
