# Generated by Django 5.1.4 on 2026-09-03 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0021_documentos_asociados'),
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_norm', models.CharField(editable=False, max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='documentos.carpetavirtual')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas_virtuales', to='organizacion.unidad')),
            ],
            options={
                'db_table': 'doc_carpeta_virtual',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCarpetaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documentos.carpetavirtual')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_carpeta', to='documentos.documento')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizacion.unidad')),
            ],
            options={
                'db_table': 'doc_documento_carpeta',
            },
        ),
        migrations.AddIndex(
            model_name='carpetavirtual',
            index=models.Index(fields=['unidad', 'padre'], name='doc_carpeta_unidad__d3c6d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='carpetavirtual',
            constraint=models.UniqueConstraint(fields=('unidad', 'padre', 'nombre_norm'), name='uq_carpeta_unidad_padre_nombre', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='documentocarpetavirtual',
            index=models.Index(fields=['carpeta'], name='doc_documen_carpeta_c21229_idx'),
        ),
        migrations.AddIndex(
            model_name='documentocarpetavirtual',
            index=models.Index(fields=['unidad', 'documento'], name='doc_documen_unidad__bf6643_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentocarpetavirtual',
            constraint=models.UniqueConstraint(fields=('documento', 'unidad'), name='uq_doc_carpeta_por_unidad'),
        ),
        # Trazabilidad F2-F (§29): el CRUD de carpetas y las clasificaciones se
        # auditan vía aud_log — NO generan SeguimientoDocumento (clasificar no
        # forma parte del recorrido institucional del documento, igual que la
        # clasificación en TRD de QUIPUX no genera hist_eventos_radicados).
        # `fn_auditoria` se engancha solo si existe (BD de test sin ella no falla).
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'fn_auditoria') THEN
                        DROP TRIGGER IF EXISTS trg_auditoria_doc_carpeta_virtual ON doc_carpeta_virtual;
                        CREATE TRIGGER trg_auditoria_doc_carpeta_virtual
                        AFTER INSERT OR UPDATE OR DELETE ON doc_carpeta_virtual
                        FOR EACH ROW EXECUTE FUNCTION fn_auditoria();

                        DROP TRIGGER IF EXISTS trg_auditoria_doc_documento_carpeta ON doc_documento_carpeta;
                        CREATE TRIGGER trg_auditoria_doc_documento_carpeta
                        AFTER INSERT OR UPDATE OR DELETE ON doc_documento_carpeta
                        FOR EACH ROW EXECUTE FUNCTION fn_auditoria();
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS trg_auditoria_doc_carpeta_virtual ON doc_carpeta_virtual;
                DROP TRIGGER IF EXISTS trg_auditoria_doc_documento_carpeta ON doc_documento_carpeta;
            """,
        ),
    ]
