= FirmaEC: firmadigital-servicio

Este proyecto implementa los servicios REST para recibir documentos desde sistemas transversales.

== Introducción

Los siguientes pasos le permitirán obtener una copia del proyecto para correrla en la máquina local para propósitos de desarrollo y pruebas.

== Prerequisitos

=== Java

Se necesita instalar _Java Development Kit (JDK) 17_ para compilar y correr la aplicación.

En Fedora se debe instalar el paquete _java-17-openjdk-devel_:

[source, bash]
----
$ sudo dnf -y install java-17-openjdk-devel
----

En Ubuntu se debe instalar el paquete _openjdk-17-jdk_.

[source, bash]
----
$ sudo apt-get install openjdk-17-jdk
----

=== Maven

Para compilar y empaquetar se utiliza https://maven.apache.org[Apache Maven] versión 3.8.8.

En _Microsoft Windows_ se debe descargar e instalar siguiendo las instrucciones de instalación de https://maven.apache.org/install.html[Apache Maven].

En _Fedora_ se debe instalar el paquete  `maven`:

[source,bash]
----
$ sudo dnf install maven
----

En _Ubuntu_ se debe instalar el paquete `maven`:

[source,bash]
----
$ sudo apt-get install maven
----

=== NetBeans

Se utilizó como entorno de desarrollo el IDE https://netbeans.org[Netbeans].

== Dependencias

Esta aplicación utiliza la librería https://minka.gob.ec/mintel/ge/firmaec/firmadigital-libreria[firmadigital-libreria] para realizar las operaciones de firma digital.

== Compilar

Se debe compilar usando el siguiente comando:

[source, bash]
----
$ mvn clean package
----

=== WildFly

Se utilizó el servidor de aplicación https://www.wildfly.org/downloads/[Wildfly].

== Desplegar

Para desplegar el proyecto _firmadigital-servicio_, se debe utilizar el servidor de aplicación Wildfly desde la versión 35.

Se debe copiar el archivo `target/servicio.war` a la carpeta `standalone/deploy` de un servidor de aplicaciones WildFly

== Desarrollo

Para facilitar el desarrollo se puede utilizar Docker. Se puede instalar las dependencias de infraestructura, como la base de datos, utilizando contenedores.

Por ejemplo, para ejecutar un servidor PostgreSQL 12, se puede ejecutar:

----
docker run -d --name postgresql_firmadigital -e POSTGRESQL_USER=firmadigital -e POSTGRESQL_PASSWORD=firmadigital -e POSTGRESQL_DATABASE=firmadigital -p 5432:5432 centos/postgresql-96-centos7
----

Se necesita un registro en la tabla "sistema" para poder probar, por ejemplo:

----
export API_KEY=$(pwgen 32 -1 | sha256sum | cut -d' ' -f1)
echo "El API-KEY a utilizar es $API_KEY"
export API_KEY_HASH=$(echo -n $API_KEY | sha256sum | cut -d' ' -f1)
echo "El HASH-256 del API-KEY, a insertar en la base de datos, es $API_KEY_HASH"
----

En la tabla "sistema" se debería insertar este hash:

----
INSERT INTO sistema(nombre,url,apikey,descripcion) values ('quipux', 'http://localhost/quipux', '$API_KEY_HASH', 'Quipux');
----

Para configurar el DataSource de PostgreSQL que apunta al contenedor, en WildFly se puede ejecutar el siguiente script para JBoss CLI:

Ejecutar `bin/jboss-cli.sh -c` y luego el siguiente script:

----
batch
module add --name=org.postgresql --resources=/home/rarguello/Downloads/postgresql-42.2.2.jar --dependencies=javax.api,javax.transaction.api

/subsystem=datasources/jdbc-driver=postgresql:add(driver-name=postgresql,driver-module-name=org.postgresql,driver-xa-datasource-class-name=org.postgresql.xa.PGXADataSource)

data-source add --name=FirmaDigitalDS --jndi-name=java:/FirmaDigitalDS --driver-name=postgresql --connection-url=jdbc:postgresql://localhost:5432/firmadigital --user-name=firmadigital --password=firmadigital --valid-connection-checker-class-name=org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLValidConnectionChecker --exception-sorter-class-name=org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLExceptionSorter

run-batch
----

== Colaborar

Para colaborar se puede enviar un _Merge Request_ utilizando la plataforma https://minka.gob.ec/mintel/ge/firmaec[Minka].

== Versiones

Usamos https://minka.gob.ec/mintel/ge/estandares/-/blob/master/versionamiento.md[Estandares] para versionar.

== Autores

* *Ricardo Arguello* - *Desarrollo* - https://www.soportelibre.com[Soporte Libre]
* *Misael Fernández* - *Desarrollo* - misael.fernandez.correa@gmail.com
* *Diana Pujol* - *Deeper* - deeperdigitalec@outlook.es

== Licencia

Esta aplicación se distribuye con una licencia https://www.gnu.org/licenses/gpl.html[GPLv3].
