# Generated by Django 5.1.4 on 2026-06-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correos', '0002_seguimientocorreo_remove_correo_tramite_and_more'),
        ('documentos', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('tramites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('anos_retencion', models.SmallIntegerField(default=5)),
                ('anos_central', models.SmallIntegerField(default=10)),
                ('disposicion_final', models.CharField(choices=[('conservacion', 'Conservación permanente'), ('eliminacion', 'Eliminación'), ('digitalizacion', 'Digitalización'), ('muestreo', 'Muestreo')], default='conservacion', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'arc_serie',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_expediente', models.CharField(max_length=60, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('num_fojas', models.IntegerField(default=0)),
                ('soporte', models.CharField(choices=[('digital', 'Digital'), ('fisico', 'Físico'), ('mixto', 'Mixto')], default='digital', max_length=20)),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('transferido', 'Transferido'), ('eliminado', 'Eliminado')], default='abierto', max_length=20)),
                ('fecha_expurgo', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='organizacion.unidad')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='archivo.serie')),
            ],
            options={
                'db_table': 'arc_expediente',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_foja', models.IntegerField(blank=True, null=True)),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('agregado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('correo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='correos.correo')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.documento')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='archivo.expediente')),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tramites.tramite')),
            ],
            options={
                'db_table': 'arc_expediente_doc',
                'ordering': ['orden_foja', 'agregado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['serie'], name='arc_expedie_serie_i_45c21a_idx'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['unidad'], name='arc_expedie_unidad__617f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['estado'], name='arc_expedie_estado_a8965e_idx'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['codigo_expediente'], name='arc_expedie_codigo__2b7ff6_idx'),
        ),
    ]
