# Generated by Django 5.1.4 on 2026-06-17 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivo', '0001_initial'),
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('valorada', 'Valorada por el equipo'), ('enviada_validacion', 'Enviada a validación'), ('dictaminada', 'Dictaminada — aprobada'), ('rechazada', 'Rechazada'), ('ejecutada', 'Ejecutada — documentos eliminados')], default='borrador', max_length=20)),
                ('caracter_proceso', models.CharField(choices=[('gobernante', 'Gobernante'), ('sustantivo', 'Sustantivo'), ('adjetivo', 'Adjetivo')], default='adjetivo', max_length=20)),
                ('justificacion', models.TextField(help_text='Por qué se propone la eliminación')),
                ('normativa_legal', models.CharField(blank=True, max_length=300)),
                ('numero_expedientes', models.IntegerField(default=0)),
                ('numero_cajas', models.IntegerField(default=0)),
                ('metros_lineales', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fecha_dictamen', models.DateField(blank=True, null=True)),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arc_baja_documental',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='BajaExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'arc_baja_exp',
            },
        ),
        migrations.CreateModel(
            name='CopiaCertificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante_nombre', models.CharField(max_length=200)),
                ('solicitante_cedula', models.CharField(blank=True, max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('numero_fojas', models.IntegerField(default=0)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arc_copia_certificada',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arc_fondo',
            },
        ),
        migrations.CreateModel(
            name='PrestamoDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion_esperada', models.DateField()),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('vencido', 'Vencido'), ('extraviado', 'Extraviado')], default='activo', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'arc_prestamo',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'arc_seccion',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('primaria', 'Primaria (Gestión → Central)'), ('secundaria', 'Secundaria (Central → Intermedio)'), ('final', 'Final (Intermedio → Histórico)')], max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('solicitada', 'Solicitada'), ('revisada', 'Revisada y cotejada'), ('aceptada', 'Aceptada — acuse de recibo'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('numero_memorando', models.CharField(blank=True, max_length=60)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('fecha_aceptacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arc_transferencia',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatura_topografica', models.CharField(blank=True, help_text='Ubicación física asignada al recibir', max_length=60)),
            ],
            options={
                'db_table': 'arc_transferencia_exp',
            },
        ),
        migrations.RemoveField(
            model_name='serie',
            name='anos_retencion',
        ),
        migrations.AddField(
            model_name='expediente',
            name='categoria_actual',
            field=models.CharField(choices=[('gestion', 'Archivo de Gestión'), ('central', 'Archivo Central'), ('intermedio', 'Archivo Intermedio'), ('historico', 'Archivo Histórico')], default='gestion', max_length=20),
        ),
        migrations.AddField(
            model_name='expediente',
            name='expurgado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_foliacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='foliado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expediente',
            name='numero_caja',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='expediente',
            name='numero_parte',
            field=models.CharField(blank=True, help_text='Ej: 1/3 si el expediente tiene varios volúmenes', max_length=10),
        ),
        migrations.AddField(
            model_name='serie',
            name='anos_gestion',
            field=models.SmallIntegerField(default=2, help_text='Años en Archivo de Gestión'),
        ),
        migrations.AddField(
            model_name='serie',
            name='base_legal',
            field=models.CharField(blank=True, help_text='Ley y artículo que determina el plazo', max_length=300),
        ),
        migrations.AddField(
            model_name='serie',
            name='condicion_acceso',
            field=models.CharField(choices=[('publico', 'Público'), ('confidencial', 'Confidencial'), ('reservado', 'Reservado')], default='publico', max_length=20),
        ),
        migrations.AddField(
            model_name='serie',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='origen_documentacion',
            field=models.CharField(choices=[('fisico', 'Físico'), ('digital', 'Digital'), ('hibrido', 'Híbrido (físico y digital)')], default='digital', max_length=20),
        ),
        migrations.AddField(
            model_name='serie',
            name='serie_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subseries', to='archivo.serie'),
        ),
        migrations.AddField(
            model_name='serie',
            name='tecnica_seleccion',
            field=models.CharField(choices=[('completa', 'Conservación completa'), ('parcial', 'Conservación parcial / muestreo'), ('na', 'No aplica')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='soporte',
            field=models.CharField(choices=[('digital', 'Digital'), ('fisico', 'Físico'), ('mixto', 'Mixto (híbrido)')], default='digital', max_length=20),
        ),
        migrations.AlterField(
            model_name='serie',
            name='anos_central',
            field=models.SmallIntegerField(default=13, help_text='Años en Archivo Central (acumulado desde gestión)'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Breve explicación del contenido de la serie (Art. 28.4.d)'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='disposicion_final',
            field=models.CharField(choices=[('conservacion', 'Conservación permanente'), ('eliminacion', 'Eliminación')], default='conservacion', max_length=20),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['categoria_actual'], name='arc_expedie_categor_8401a8_idx'),
        ),
        migrations.AddField(
            model_name='bajadocumental',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bajadocumental',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bajadocumental',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas_documentales', to='organizacion.unidad'),
        ),
        migrations.AddField(
            model_name='bajaexpediente',
            name='baja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='archivo.bajadocumental'),
        ),
        migrations.AddField(
            model_name='bajaexpediente',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas', to='archivo.expediente'),
        ),
        migrations.AddField(
            model_name='copiacertificada',
            name='certificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='copiacertificada',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copias_certificadas', to='archivo.expediente'),
        ),
        migrations.AddField(
            model_name='prestamodocumental',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamodocumental',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='archivo.expediente'),
        ),
        migrations.AddField(
            model_name='prestamodocumental',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seccion',
            name='fondo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones', to='archivo.fondo'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='seccion_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsecciones', to='archivo.seccion'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones_archivo', to='organizacion.unidad'),
        ),
        migrations.AddField(
            model_name='serie',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='archivo.seccion'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='organizacion.unidad'),
        ),
        migrations.AddField(
            model_name='transferenciaexpediente',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='archivo.expediente'),
        ),
        migrations.AddField(
            model_name='transferenciaexpediente',
            name='transferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='archivo.transferencia'),
        ),
        migrations.AlterUniqueTogether(
            name='bajaexpediente',
            unique_together={('baja', 'expediente')},
        ),
        migrations.AlterUniqueTogether(
            name='transferenciaexpediente',
            unique_together={('transferencia', 'expediente')},
        ),
    ]
