# Generated by Django 5.1.4 on 2026-06-17 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivo', '0002_bajadocumental_bajaexpediente_copiacertificada_fondo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='archivo.seccion'),
        ),
    ]
